### ISSUE TITLE
how to use third party speech to text conversion in existing lex web ui logic 

### ISSUE THREAD

**Issue by tusharIndore** [awslabs/aws-lex-web-ui#14]
For address translation and for all speech to text translation , I want to use third party api such as google speech api then after getting correct address in text form I want to send text address to amazon lex by using same lex web UI interface. How this can be incorporated in your existing logic.
If this is possible please share code for it.

**Comment by atoa** [comment]
Hi Tushar,

You can create a Lambda function to use as a code hook for you Amazon Lex bot. From the Lambda function, you can call third-party APIs and pass them the fields received in the [input event](http://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html#using-lambda-input-event-format) (e.g. slots, message text/transcript, session attributes).

You can include the output of those API calls in the bot responses. For code examples, please take a look at the [Using Lambda Functions](http://docs.aws.amazon.com/lex/latest/dg/using-lambda.html) section of the Lex documentation.

Let me know if this clarifies it

-- Oliver

**Comment by tusharIndore** [comment]
Hi Oliver,

Thanks for your reply.
When we press mic button to capture voice from UI then google api should be called for capturing voice and result into text form. After getting text result,the request should go to lex for fulfillment.

I want to implement above scenario in existing lex-web-ui app otherwise I have to write code from scratch. Give me idea of file in which  I need to make changes for calling google api for capturing voice and make the process in sync.

Thanks,
Tushar Choudhary

**Comment by atoa** [comment]
Hi Tushar,

This project is not intended to be used in the scenario you describe and would require major changes to implement it. Third party API integrations are meant to be done in the back-end using a Lambda function as described in the previous correspondence.

We are unable to provide a list of files that would need to be modified since implementing this change would probably require significant changes to various files. I am closing this ticket as I believe that the intended third-party API integration mechanism has been clarified. Feel free to re-open if you need further info.

-- Oliver
