### ISSUE TITLE
Sending multiple messages to User

### ISSUE THREAD

**Issue by baendron** [awslabs/aws-lex-web-ui#19]
Hi, I'm very new to Lex and still in the process of learning how to get it to work properly. I've just recently deployed my bot via an Amazon S3 static webpage. I was wondering if it is possible to send multiple messages to the user with each containing information that the user requested. 

For example, (my bot takes input from the user and runs a SQL search through a RDS instance)
if the User wants to search for events via their ID number, would it be possible to display the results of said search via a series of messages, with each message containing one result?

I'm only asking this because my bot doesn't display line breaks in the output. Please see the following image to see what I mean:
![lex output ](https://user-images.githubusercontent.com/32186122/34348309-cb556c6e-ea44-11e7-9e33-236c49eae8d8.png)

this is despite my Lambda function (written in C#) having the `\n` line break in the output method. How can I get the bot to display each result on its own line, if that's possible?

**Comment by atoa** [comment]
Hello

> this is despite my Lambda function (written in C#) having the \n line break in the output method. How can I get the bot to display each result on its own line, if that's possible?

This is due to the bot response content being ultimately incorporated as HTML. In HTML, the `\n` character is not rendered as a line break. You normally use `<br>` tags for line breaks in HTML.

However, the chatbot UI doesn't currently support HTML tags in messages. We are tracking a feature request to support rendering basic HTML tags or markdown in the bot responses. See item 3 in: https://github.com/awslabs/aws-lex-web-ui/issues/7. This is a feature we are considering to implement in the future.

Possible alternatives include:
1. Break up the list into a dialog (e.g. *[bot:]* "You have 3 active events. Do you want details about these events?" > *[user:]* "yes" > *[bot:]* "The latest event, ID 32, is .... Do you want to change this event or hear about the next one?'" ). This is also useful if you want to avoid long responses when using speech. See [Building Better Bots](https://aws.amazon.com/blogs/ai/building-better-bots/) for some dialog design considerations
2. Use [Response Cards](http://docs.aws.amazon.com/lex/latest/dg/ex-resp-card.html) to visually organize the response data. You could render items as buttons or have a response card with multiple [Generic Attachments](http://docs.aws.amazon.com/lex/latest/dg/API_runtime_GenericAttachment.html)
3. Modify the [Message.vue](https://github.com/awslabs/aws-lex-web-ui/blob/master/lex-web-ui/src/components/MessageText.vue) file to implement a custom rendering logic

I hope this helps

-- Oliver

**Comment by baendron** [comment]
Hi Oliver, thanks for the prompt response. You said break up the list into a dialog. Would that be a ConfirmIntent? As far as I know, LexResponse can only be one of the following:

Delegate
ElicitIntent
ElicitSlot
ConfirmIntent
Close

**Comment by baendron** [comment]
UPDATE:
Sorry to keep posting updates but I managed to fix the issue. Thanks a lot for your help Oliver!

**Comment by stevejwebb** [comment]
Hi is this still open? Where do I find the Message.vue file?
Thanks.

**Comment by bobpskier** [comment]
Yes still open. I’ll see if I can generate a fix for this. Message.vue is at lex-web-ui/src/components/Message.vue. The actual fix will probably be in lex-web-ui/src/store/actions.js where the response from Lex is parsed and a new Message is constructed that is placed in the MessageList. This area needs to be updated to handle an array of messages in the response.

**Comment by prashant1145** [comment]
> 
> 
> Hi Oliver, thanks for the prompt response. You said break up the list into a dialog. Would that be a ConfirmIntent? As far as I know, LexResponse can only be one of the following:
> 
> Delegate
> ElicitIntent
> ElicitSlot
> ConfirmIntent
> Close
> 
> Also, can you explain how to attach the ResponseCard to the message? Mine doesn't seem to show at all:
> ![lex 4](https://user-images.githubusercontent.com/32186122/34397082-9c570354-ebad-11e7-8109-322dcd2b94ed.png)
> 
> UPDATE:
> I've managed to modify the Message.vue file so that the bot displays the HTML tags properly. The only issue now is that when I click a link in the message, the index.html that the iframe references is updated instead of the parent page. Can you provide any help to help me fix this?
> 
> Before I click the link:
> ![lex 6](https://user-images.githubusercontent.com/32186122/34398584-082f4cc8-ebbb-11e7-8648-f6534f6eec56.png)
> 
> After I click the link:
> ![lex 5](https://user-images.githubusercontent.com/32186122/34398586-0f588a5a-ebbb-11e7-8a9c-c684b3a47e34.png)

How did you format your output,each on new line????
please show the sample code

**Comment by ShijunL** [comment]
\n and <br> both not working, please, anybody give a fix? thanks.
