### ISSUE TITLE
Custom Bot Deployment - Web Ui is not changing 

### ISSUE THREAD

**Issue by kanthedgaurav** [awslabs/aws-lex-web-ui#2]
I deployed my custom bot and changed src/index.js to change bot title , color but it is still taking order flowers. Bot is working fine even though.

**Comment by atoa** [comment]
Changing the src/index.js will not update the bot title, color, etc. Please take a look at the [Configuration and Customization](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#configuration-and-customization) section of the README file for details on how to change those fields.

Let me know if that clarifies it.

**Comment by kanthedgaurav** [comment]
Thanks for your reply ! 
Sorry , i'm not getting you . I looked Configuration and Customization section of the README file but not able to understand .

Let me elaborate what I did so far .
1. Spin up EC2
2. clone this git
3. created new s3 directory
4. changed bucket_name on templates/master.yaml file  (mappings section)
5. chnaged src/index.file and give bot name test_bot and other parameters according to  ( test_bot is exist on my aws account)
6. change bucket name and bot name on build/config.env
7. run make upload under build folder 
6. spin up cloud formation 
7. passed my bot name test_bot
8 . my bot is working fine on web-ui , only issue it is still showing order flowers on heading , page and initial question.

Thanks for your help !

**Comment by atoa** [comment]
I am going to assume that in step #5) above you meant that you are trying to change the `src/config/index.js` file (correct me if I am wrong). Have you changed the `src/config/config.prod.json` file?

If the answer is no, then your changes to the index.js are probably being overridden at build time by the existing default values in `config.prod.json` which takes precedence.

Please note that the `src/config/index.js` is meant to be a base default config. In most cases, you probably don't want to be making changes to `src/config/index.js` since that would make it harder to merge future changes. Instead, try to make your config changes in the JSON config file: `src/config/config.prod.json` or use the other dynamic configuration mechanisms (e.g. url params).

Sorry that the README is not very clear. I am going to clarify the instructions. For now, Please let me know if changing the config.prod.json file fixes it.

**Comment by kanthedgaurav** [comment]
unfortunately , it is not working even if i'm making change only to src/config/config.prod.json file .
<code>
$ cat config.prod.json
{
  "cognito": {
    "poolId": ""
  },
  "lex": {
    "botName": "test",
    "initialText": "Welcome to test Bot. Just type \"Tracking\" or click on the mic and say it.",
    "initialSpeechInstruction": "Say 'Tracking' to get started."
  },
  "polly": {
    "voiceId": "Salli"
  },
  "ui": {
    "parentOrigin": "",
    "pageTitle": "test",
    "toolbarTitle": "test"
  },
  "recorder": {
    "preset": "speech_recognition"
  }
}
</code>

**Comment by atoa** [comment]
For the build time parameters to take effect, you have to rebuild the application. When using the pages created by the sample CloudFormation stack, you have to push changes through the [deployment pipeline](https://github.com/awslabs/aws-lex-web-ui#deployment-pipeline) to rebuild the component. So your changes would have to be pushed to the CodeCommit repo created by the CloudFormation stack in order to take effect.

You can also test your changes locally using npm before pushing them to the CodeCommit repo. See the [Dependencies and Build Setup](https://github.com/awslabs/aws-lex-web-ui/tree/master/lex-web-ui#dependencies-and-build-setup) section of the web component readme. In specific, from the `lex-web-ui` sub-directory, you can run `npm run dev` to run a development server in your machine (assuming that you have installed it with `npm install`).

The other option (which may be easier than the process described above) is to pass the parameters dynamically at run time (instead of build time). This includes passing the parameters in the URL or via events (when running as an iframe). I pushed some clarifications to the [Configuration and Customization](https://github.com/awslabs/aws-lex-web-ui/tree/development/lex-web-ui#configuration-and-customization). Please take a look and see if that helps.

Are you pushing these changes to the CodeCommit repo created by the pipeline or have you used `npm run dev` locally in your machine to see the changes?  Please let me know how you are pushing the changes or if passing the parameters dynamically (e.g. url) helps.

**Comment by kanthedgaurav** [comment]
Thanks for your help !

It is working now . it seems to me that there is some issue with make upload . it is uploading src.zip with all default values instead of custom bucket name , bot name . I downloaded src.zip from my s3 bucket and modified /build/config, /src/config.prod.json and /templates/master.yaml with my bucket name , again zip it and upload it and deployed using cloud formation . 

You did awesome work to integrate existing bot to web . 

Thank you once again !

**Comment by atoa** [comment]
Great to hear! Stay tuned, we are working on changes to make customization and deployments easier.

Thanks for the feedback.
